# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 12:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('created', models.DateField(auto_now_add=True)),
                ('units', models.CharField(choices=[('g', 'gramms'), ('mg', 'milligramms'), ('kg', 'kilogramms'), ('pc', 'pieces'), ('l', 'liter'), ('ml', 'milliliter')], default='g', max_length=2)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['title', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ComponentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Component', unique_for_date='date')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_link', models.TextField(blank=True, default='')),
                ('created', models.DateField(auto_now_add=True)),
                ('units', models.CharField(choices=[('g', 'gramms'), ('mg', 'milligramms'), ('kg', 'kilogramms'), ('pc', 'pieces'), ('l', 'liter'), ('ml', 'milliliter')], default='pc', max_length=2)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['title', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item', unique_for_date='date')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('cc', 'credit card'), ('cheque', 'cheque')], default='cc', max_length=6)),
                ('items', models.ManyToManyField(through='api.OrderContent', to='api.Item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='ordercontent',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrderDetail'),
        ),
    ]
