# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160527_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
