# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160527_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='ordercontent',
            unique_together=set([('order', 'item')]),
        ),
    ]
