# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160527_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='api.Item'),
        ),
    ]
