# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_items'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordercontent',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ordercontent',
            name='item',
        ),
        migrations.RemoveField(
            model_name='ordercontent',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderContent',
        ),
    ]
