# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160626_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercomposition',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='ordercomposition',
            old_name='order',
            new_name='order_id',
        ),
    ]
